<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="pranjal" failures="0" tests="2" name="com.xuriti.api_Auth_Service.TC_03_verify_otp" time="1.557" errors="0" timestamp="2022-12-05T14:04:51 IST" skipped="0">
  <testcase classname="com.xuriti.api_Auth_Service.TC_03_verify_otp" name="TC_1_Sign_In_INvalid_otp" time="1.497"/>
  <system-out/>
  <testcase classname="com.xuriti.api_Auth_Service.TC_03_verify_otp" name="TC_2_Sign_In_with_correct_otp" time="0.060"/>
  <system-out/>
</testsuite> <!-- com.xuriti.api_Auth_Service.TC_03_verify_otp -->
